codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "99...100"
  status:
    project:
        default:
          target: auto
          threshold: 1%
          base: auto
    patch:
      default:
        threshold: 1%
